export enum InvestmentType {
  // Renda Fixa - Tesouro Direto
  TESOURO_SELIC = 'TESOURO_SELIC',
  TESOURO_PREFIXADO = 'TESOURO_PREFIXADO',
  TESOURO_IPCA = 'TESOURO_IPCA',

  // Renda Fixa - Emissão Bancária
  POUPANCA = 'POUPANCA',
  CDB_DI = 'CDB_DI',
  CDB_PREFIXADO = 'CDB_PREFIXADO',
  CDB_HIBRIDO = 'CDB_HIBRIDO',
  LCI = 'LCI',
  LCA = 'LCA',
  LCD = 'LCD',

  // Renda Fixa - Crédito Privado
  DEBENTURES_SIMPLES = 'DEBENTURES_SIMPLES',
  DEBENTURES_INCENTIVADAS = 'DEBENTURES_INCENTIVADAS',
  CRI = 'CRI',
  CRA = 'CRA',

  // Renda Fixa - Fundos
  FUNDOS_RENDA_FIXA_SIMPLES = 'FUNDOS_RENDA_FIXA_SIMPLES',
  FUNDOS_RENDA_FIXA_CREDITO_PRIVADO = 'FUNDOS_RENDA_FIXA_CREDITO_PRIVADO',

  // Renda Variável - Ações
  ACOES_NACIONAIS = 'ACOES_NACIONAIS',
  BLUE_CHIPS = 'BLUE_CHIPS',
  MID_CAPS = 'MID_CAPS',
  SMALL_CAPS = 'SMALL_CAPS',
  UNITS = 'UNITS',

  // Renda Variável - FIIs
  FUNDOS_IMOBILIARIOS_TIJOLO = 'FUNDOS_IMOBILIARIOS_TIJOLO',
  FUNDOS_IMOBILIARIOS_PAPEL = 'FUNDOS_IMOBILIARIOS_PAPEL',
  FUNDOS_IMOBILIARIOS_HIBRIDOS = 'FUNDOS_IMOBILIARIOS_HIBRIDOS',
  FUNDOS_IMOBILIARIOS_DESENVOLVIMENTO = 'FUNDOS_IMOBILIARIOS_DESENVOLVIMENTO',
  FUNDOS_FIAGRO = 'FUNDOS_FIAGRO',

  // Renda Variável - ETFs e BDRs
  ETFs_NACIONAIS = 'ETFs_NACIONAIS',
  BDRS_NIVEL_1 = 'BDRS_NIVEL_1',
  BDRS_NIVEL_2 = 'BDRS_NIVEL_2',
  BDRS_NIVEL_3 = 'BDRS_NIVEL_3',

  // Fundos de Investimento
  FUNDOS_MULTIMERCADO = 'FUNDOS_MULTIMERCADO',
  FUNDOS_LONG_SHORT = 'FUNDOS_LONG_SHORT',
  FUNDOS_MACRO = 'FUNDOS_MACRO',
  FUNDOS_QUANTITATIVOS = 'FUNDOS_QUANTITATIVOS',
  FUNDOS_ACOES = 'FUNDOS_ACOES',
  FUNDOS_SETORIAIS = 'FUNDOS_SETORIAIS',
  FUNDOS_CAMBIAIS = 'FUNDOS_CAMBIAIS',
  FUNDOS_IMOBILIARIOS = 'FUNDOS_IMOBILIARIOS',

  // Internacional - Renda Variável
  ACOES_INTERNACIONAIS = 'ACOES_INTERNACIONAIS',
  ETFs_INTERNACIONAIS = 'ETFs_INTERNACIONAIS',
  REITS = 'REITS',

  // Internacional - Renda Fixa
  BONDS_INTERNACIONAIS = 'BONDS_INTERNACIONAIS',
  TREASURIES_EUA = 'TREASURIES_EUA',

  // Internacional - Fundos
  FUNDOS_OFFSHORE = 'FUNDOS_OFFSHORE',
  HEDGE_FUNDS = 'HEDGE_FUNDS',
  PRIVATE_EQUITY_GLOBAL = 'PRIVATE_EQUITY_GLOBAL',

  // Criptoativos
  BITCOIN = 'BITCOIN',
  ETHEREUM = 'ETHEREUM',
  ALTCOINS = 'ALTCOINS',
  STABLECOINS = 'STABLECOINS',
  TOKENS_DEFI = 'TOKENS_DEFI',
  YIELD_FARMING = 'YIELD_FARMING',
  STAKING = 'STAKING',
  LIQUID_STAKING = 'LIQUID_STAKING',
  NFTs = 'NFTs',
  METAVERSO_TOKENS = 'METAVERSO_TOKENS',

  // Commodities - Metais
  OURO_FISICO = 'OURO_FISICO',
  OURO_PAPEL = 'OURO_PAPEL',
  PRATA = 'PRATA',
  COBRE = 'COBRE',

  // Commodities - Energia
  PETROLEO = 'PETROLEO',
  GAS_NATURAL = 'GAS_NATURAL',

  // Commodities - Agrícolas
  AGRICOLAS_SOJA = 'AGRICOLAS_SOJA',
  AGRICOLAS_MILHO = 'AGRICOLAS_MILHO',
  AGRICOLAS_CAFE = 'AGRICOLAS_CAFE',
  AGRICOLAS_BOI = 'AGRICOLAS_BOI',

  // Imobiliário
  IMOVEIS_RESIDENCIAIS = 'IMOVEIS_RESIDENCIAIS',
  IMOVEIS_COMERCIAIS = 'IMOVEIS_COMERCIAIS',
  TERRENOS = 'TERRENOS',
  IMOVEIS_PARA_RENDA = 'IMOVEIS_PARA_RENDA',
  IMOVEIS_PARA_FLIP = 'IMOVEIS_PARA_FLIP',
  FLORESTAS = 'FLORESTAS',
  ENERGIA_RENOVAVEL = 'ENERGIA_RENOVAVEL',

  // Alternativos
  PRIVATE_EQUITY = 'PRIVATE_EQUITY',
  VENTURE_CAPITAL = 'VENTURE_CAPITAL',
  INVESTIMENTO_ANJO = 'INVESTIMENTO_ANJO',
  CROWDFUNDING_EQUITY = 'CROWDFUNDING_EQUITY',
  FIDCS = 'FIDCS',
  COES = 'COES',
  DERIVATIVOS = 'DERIVATIVOS',
  OPCOES = 'OPCOES',
  FUTUROS = 'FUTUROS',
  SWAPS = 'SWAPS',

  // Previdência
  PREVIDENCIA_PRIVADA_PGBL = 'PREVIDENCIA_PRIVADA_PGBL',
  PREVIDENCIA_PRIVADA_VGBL = 'PREVIDENCIA_PRIVADA_VGBL',
  PLANO_DE_APOSENTADORIA_EMPRESARIAL = 'PLANO_DE_APOSENTADORIA_EMPRESARIAL',
  SEGURO_DE_VIDA_RESGATAVEL = 'SEGURO_DE_VIDA_RESGATAVEL',

  // Colecionáveis
  OBRAS_DE_ARTE = 'OBRAS_DE_ARTE',
  VINHOS = 'VINHOS',
  RELOGIOS = 'RELOGIOS',
  CARROS_CLASSICOS = 'CARROS_CLASSICOS',
  JOIAS = 'JOIAS',
  COLECIONAVEIS = 'COLECIONAVEIS',
}
